### ISSUE TITLE
ImportError: cannot import name rnn_cell

### ISSUE THREAD

**Issue by IvyGongoogle** [zhiguowang/BiMPM#1]
hello, When I run the command `python BiMPM/src/SentenceMatchTrainer.py`, it shows error:

```
Traceback (most recent call last):
  File "BiMPM/src/SentenceMatchTrainer.py", line 12, in <module>
    from SentenceMatchModelGraph import SentenceMatchModelGraph
  File "/home/xxx/BiMPM/src/SentenceMatchModelGraph.py", line 2, in <module>
    import my_rnn
  File "/home/xxx/BiMPM/src/my_rnn.py", line 12, in <module>
    from tensorflow.python.ops import rnn_cell
ImportError: cannot import name rnn_cell
```
can you update your code for tensorflow1.0. 
thank you very much!!

**Comment by joshuaeckroth** [comment]
IvyGongoogle, look at my pull request: https://github.com/zhiguowang/BiMPM/pull/2
