### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'has_key'

### ISSUE THREAD

**Issue by tamio96** [zhiguowang/BiMPM#51]
I got this error when run:
 python SentenceMatchTrainer.py --config_path /home/tamiomusic/BiMPM/con
figs/quora.sample.config 

I only change `quora.sample.config` to fix with files' directory:
    "train_path": "/home/tamiomusic/BiMPM/quora/train.tsv",
    "dev_path": "/home/tamiomusic/BiMPM/quora/dev.tsv",
    "word_vec_path": "/home/tamiomusic/BiMPM/quora/wordvec.txt",
    "model_dir": "/home/tamiomusic/BiMPM/quora/logs"

Full log:
Loading the configuration from /home/tamiomusic/BiMPM/configs/snli.sample.config
Traceback (most recent call last):
  File "SentenceMatchTrainer.py", line 251, in <module>
    FLAGS = enrich_options(FLAGS)
  File "SentenceMatchTrainer.py", line 201, in enrich_options
    if not options.__dict__.has_key("in_format"):
AttributeError: 'dict' object has no attribute 'has_key'

Best regards,

**Comment by guotong1988** [comment]
python2, not python3
